language: android
cache: false
sudo: false
jdk:
 - oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra
    - add-on
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28

before_script:
  - chmod +x ./gradlew
  # - android list targets
  - echo no | android create avd --force -n test -t android-28
  - emulator -avd test -no-window &
  # - emulator -list-avds
  # - android-wait-for-emulator
  # - adb shell input keyevent 82 &

script:
  - ./wait_for_emulator
  - ./gradlew connectedCheck -PdisablePreDex
